basePath: /v1
definitions:
  entity.GasDayAverageResult:
    properties:
      average:
        type: number
      date:
        example: 22-01-01 00:00
        type: string
    type: object
  entity.GasHourFreqResult:
    properties:
      hour:
        maximum: 24
        minimum: 0
        type: integer
      value:
        type: number
    type: object
  entity.GasMonthAmountResult:
    properties:
      amount:
        type: number
      date:
        example: 22-01-01 00:00
        type: string
    type: object
  entity.GasResult:
    properties:
      gasHourFreq:
        items:
          $ref: '#/definitions/entity.GasHourFreqResult'
        type: array
      gasPerDayAverage:
        items:
          $ref: '#/definitions/entity.GasDayAverageResult'
        type: array
      gasPerMonthAmount:
        items:
          $ref: '#/definitions/entity.GasMonthAmountResult'
        type: array
      gasSpentTotal:
        type: number
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
info:
  contact: {}
  title: Gas Price Test Task
  version: "1.0"
paths:
  /graph:
    get:
      consumes:
      - application/json
      operationId: get-graph
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.GasResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Get gas statistic graph
swagger: "2.0"
